NODE_ENV = development

PORT=5000

MONGO_URI = mongodb://127.0.0.1:27017/lms

JWT_SECRET = node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
JWT_EXPIRY=3600


CLOUDINARY_CLOUD_NAME = dqb7bccpo
CLOUDINARY_API_KEY = 228734144465562
CLOUDINARY_API_SECRET = 9A1Om-F3psvJhvTRexCiYom6s_0

SMTP_HOST = <YOUR_SMTP_HOST>
SMTP_PORT = <YOUR_SMTP_PORT>
SMTP_USERNAME = <YOUR_SMTP_USERNAME>
SMTP_PASSWORD = <YOUR_SMTP_PASSWORD>
SMTP_FROM_EMAIL = <YOUR_SMTP_FROM_EMAIL>

RAZORPAY_KEY_ID = rzp_test_FyigA49kWp9DaV
RAZORPAY_SECRET = vvcV5XYSSwRgrBxkN03yCtl9
RAZORPAY_PLAN_ID = plan_NTMvE1fVFJXBdl

FRONTEND_URL = <YOUR_FRONTEND_WEBSITE_URL>

CONTACT_US_EMAIL = sainirohan830@gmail.com